### ISSUE TITLE
Error when renewing cert - 404: Project Not Found

### ISSUE THREAD

**Issue by sirtimbly** [zongren/gitlab-letsencrypt-hexo#1]
I'm guessing this is a message from the L.E. API - but I'm not sure - is it coming from gitlab? Also it looks like there's some API changes that need to be implemented? It showed those messages when I used it a couple months ago, but it still worked. I've successfully set up 3 domains using this tool, but have not had to try renewing yet.

```
gitlab-le-hexo \
--email      xxxxx@gmail.com \
--domain     terribleaudio.com    \
--repository xxxxxxx/terrible-audio \
--token         xxxxxxxxxxxxxxxxx
This Let's Encrypt / ACME server has been updated with urls that this client doesn't understand
{ 'key-change': 'https://acme-v01.api.letsencrypt.org/acme/key-change',
  'new-authz': 'https://acme-v01.api.letsencrypt.org/acme/new-authz',
  'new-cert': 'https://acme-v01.api.letsencrypt.org/acme/new-cert',
  'new-reg': 'https://acme-v01.api.letsencrypt.org/acme/new-reg',
  'revoke-cert': 'https://acme-v01.api.letsencrypt.org/acme/revoke-cert' }
404 - {"message":"404 Project Not Found"}
```

**Comment by zongren** [comment]
This tool is modified from [gitlab-letsencrypt](https://github.com/rolodato/gitlab-letsencrypt),and I haven't used it for a long time, I will have a look at it though.

**Comment by zongren** [comment]
You could try to submit an issue at [gitlab-letsencrypt](https://github.com/rolodato/gitlab-letsencrypt)

**Comment by zongren** [comment]
@sirtimbly 
I have made a pull request at [letiny-core](https://github.com/martinheidegger/letiny-core/pull/1),it should fix the warning
