### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by egorzot** [zongren/gitlab-letsencrypt-hexo#2]
Hi!
I get an error
```
/usr/bin/env: ‘node\r’: No such file or directory
```
try to fix with this in vim for /usr/local/lib/node_modules/gitlab-letsencrypt-hexo/index.js

```
:set ff=unix
```
but it doesn't help.

Symlink /usr/bin/node is created. Node version 7.9.0.

**Comment by zongren** [comment]
can you try other versions of node,say 6.10.2

**Comment by zongren** [comment]
and which os did you use

**Comment by egorzot** [comment]
os is ubuntu 16.04

> can you try other versions of node,say 6.10.2

not solving the problem ([screenshot](https://s.mail.ru/Dg2k/7oJuthnnC))
Node installed via nvm

**Comment by zongren** [comment]
@egorzot I cannot find any `\r` symbol in `index.js`

**Comment by zongren** [comment]
can you resintall it

**Comment by egorzot** [comment]
> can you reinstall it

It doesn't help.

**Comment by zongren** [comment]
can you try the following code
```
vim index.js
:set ff=unix
:wq
```

**Comment by egorzot** [comment]
Yes, get this error after that
https://s.mail.ru/DZr9/p5iJzLief

**Comment by zongren** [comment]
I got this error too,I'm afraid I need more time to fix this error

**Comment by zongren** [comment]
Reinstalling it should do
